//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Unit
    {
        public int Prod_Id { get; set; }
        public string Prod_Unit { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
