//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply_Permission()
        {
            this.Supply_Permission_Product = new HashSet<Supply_Permission_Product>();
        }
    
        public int Per_Id { get; set; }
        public Nullable<System.DateTime> Per_Date { get; set; }
        public string War_Name { get; set; }
        public string Sup_Name { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply_Permission_Product> Supply_Permission_Product { get; set; }
    }
}
