//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Permission_Product
    {
        public int Per_Id { get; set; }
        public int Prod_Id { get; set; }
        public string Prod_Name { get; set; }
        public Nullable<int> Prod_Quantity { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supply_Permission Supply_Permission { get; set; }
    }
}
